-- ============================================================
-- MIGRATION 015: AI Daily Usage Tracking
-- Tujuan: Mencegah abuse endpoint LLM (Gemini/DeepSeek) dengan 
--          membatasi jumlah request per user per hari.
-- ============================================================

-- 1. Tabel untuk tracking usage harian per user
CREATE TABLE IF NOT EXISTS public.ai_daily_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  usage_date DATE NOT NULL DEFAULT CURRENT_DATE,
  request_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Satu row per user per hari
  CONSTRAINT ai_daily_usage_user_date_unique UNIQUE (user_id, usage_date),
  CONSTRAINT ai_daily_usage_user_fk FOREIGN KEY (user_id) REFERENCES public.user(id) ON DELETE CASCADE
);

-- 2. Index untuk lookup cepat
CREATE INDEX IF NOT EXISTS idx_ai_daily_usage_user_date
  ON public.ai_daily_usage (user_id, usage_date);

-- 3. Trigger untuk auto-update updated_at
CREATE OR REPLACE FUNCTION trigger_ai_daily_usage_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ai_daily_usage_updated_at ON public.ai_daily_usage;
CREATE TRIGGER trg_ai_daily_usage_updated_at
  BEFORE UPDATE ON public.ai_daily_usage
  FOR EACH ROW
  EXECUTE FUNCTION trigger_ai_daily_usage_updated_at();

-- 4. RPC function: Atomic increment + upsert
--     Menggunakan INSERT ... ON CONFLICT untuk atomicity
CREATE OR REPLACE FUNCTION public.increment_ai_daily_usage(
  p_user_id BIGINT,
  p_date DATE
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_count INT;
BEGIN
  INSERT INTO public.ai_daily_usage (user_id, usage_date, request_count)
  VALUES (p_user_id, p_date, 1)
  ON CONFLICT (user_id, usage_date)
  DO UPDATE SET
    request_count = public.ai_daily_usage.request_count + 1,
    updated_at = now()
  RETURNING public.ai_daily_usage.request_count INTO v_count;

  RETURN v_count;
END;
$$;

-- 5. Enable RLS (opsional — table ini diakses via service role, bukan anon)
ALTER TABLE public.ai_daily_usage ENABLE ROW LEVEL SECURITY;

-- 6. Hanya service role yang boleh baca/tulis
CREATE POLICY "Service role can manage ai_daily_usage"
  ON public.ai_daily_usage
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 7. Comment
COMMENT ON TABLE public.ai_daily_usage IS 'Menyimpan jumlah request AI/LLM per user per hari untuk membatasi abuse (daily cap = 30 request/user/hari)';
COMMENT ON COLUMN public.ai_daily_usage.request_count IS 'Jumlah kumulatif request AI hari ini untuk user ini';