// app/api/register/route.ts
// Ini adalah API Route sisi server untuk pendaftaran pengguna kustom.

import { createClient } from '@supabase/supabase-js';
import { NextRequest, NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid'; // Untuk menghasilkan ID unik jika public.user.id bukan serial

// Mendapatkan variabel lingkungan
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseServiceRoleKey) {
  console.error('ERROR: Variabel lingkungan Supabase (URL atau Service Role Key) tidak ditemukan untuk route register.');
  throw new Error('Missing environment variables for register API route.');
}

const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
    detectSessionInUrl: false,
  },
});

export async function POST(req: NextRequest) {
  console.log('--- Memulai Permintaan Register API ---');
  try {
    const { email, password, username } = await req.json(); // Asumsi menerima username juga

    if (!email || !password || !username) {
      console.log('[LOG] Email, password, atau username tidak ada.');
      return NextResponse.json({ error: 'Email, password, dan username wajib diisi.' }, { status: 400 });
    }

    // 1. Periksa apakah email atau username sudah ada di public.user
    console.log(`[LOG] Memeriksa ketersediaan email: ${email} dan username: ${username}`);
    const { data: existingUsers, error: checkError } = await supabaseAdmin
      .from('user')
      .select('id, email, username')
      .or(`email.eq.${email},username.eq.${username}`);

    if (checkError) {
      console.error('[LOG] ERROR saat memeriksa pengguna yang sudah ada:', checkError.message);
      return NextResponse.json({ error: 'Terjadi kesalahan saat memeriksa pengguna.' }, { status: 500 });
    }

    if (existingUsers && existingUsers.length > 0) {
      if (existingUsers.some(u => u.email === email)) {
        console.log(`[LOG] Pendaftaran gagal: Email ${email} sudah terdaftar.`);
        return NextResponse.json({ error: 'Email sudah terdaftar.' }, { status: 409 }); // Conflict
      }
      if (existingUsers.some(u => u.username === username)) {
        console.log(`[LOG] Pendaftaran gagal: Username ${username} sudah digunakan.`);
        return NextResponse.json({ error: 'Username sudah digunakan.' }, { status: 409 }); // Conflict
      }
    }

    // 2. Hash password
    console.log('[LOG] Menghash password...');
    const saltRounds = 10; // Jumlah putaran salt untuk bcrypt
    const hashedPassword = await bcrypt.hash(password, saltRounds);
    console.log('[LOG] Password berhasil dihash.');

    // 3. Sisipkan pengguna baru ke tabel public.user
    // Catatan: Jika 'id' di public.user adalah BIGINT GENERATED BY DEFAULT AS IDENTITY,
    // maka Anda TIDAK perlu menyediakan 'id' di sini; Supabase akan mengaturnya.
    // Jika 'id' adalah UUID, Anda mungkin perlu membuat satu di sini (misal: uuidv4()).
    const newUser = {
      // id: uuidv4(), // Gunakan ini jika 'id' adalah UUID dan Anda perlu membuatnya manual
      email: email,
      password_hash: hashedPassword,
      username: username,
      role: 'alumni', // Set role default atau dari input pengguna
    };

    console.log('[LOG] Menyisipkan pengguna baru ke public.user...');
    const { error: insertError } = await supabaseAdmin
      .from('user')
      .insert([newUser]);

    if (insertError) {
      console.error('[LOG] ERROR saat menyisipkan pengguna baru ke public.user:', insertError.message);
      return NextResponse.json({ error: 'Gagal mendaftar pengguna.' }, { status: 500 });
    }

    console.log(`[LOG] Pengguna ${email} berhasil didaftarkan di public.user.`);
    console.log('--- Permintaan Register API Selesai ---');
    return NextResponse.json({ message: 'Pendaftaran berhasil!' }, { status: 201 }); // Created

  } catch (error: any) {
    console.error('[LOG] ERROR FATAL di Register API Route:', error.message);
    return NextResponse.json({ error: 'Terjadi kesalahan internal server.' }, { status: 500 });
  }
}
